version: '2'
services:
  frontend:
    build: ./frontend
    environment:
     PORT: 8080
     BACKEND: "backend"
    ports:
     - "8000:8080"
    links:
     - backend
  backend:
    build: ./backend
    environment:
     DATABASE_CONNECTION: "postgresql://postgres:mysecretpassword@db/docker-test-project"
    links:
     - db
  db:
    image: postgres
    volumes_from:
     - data
    environment:
     - POSTGRES_PASSWORD=mysecretpassword
  data:
    image: busybox
    volumes:
     - "/var/lib/postgresql"
