version: '2'
services:
  frontend:
    build: ./frontend
    environment:
     PORT: 8080
     BACKEND: "backend"
    ports:
     - "8000:8080"
    links:
     - backend
  backend:
    build: ./backend
